################################################################################
# Spork Configuration File.
# 
# Please read this file over and set the values to your own.
#
# If you want global settings for all your slideshows, copy this file to
# ~/.sporkrc/config.yaml. Any settings in this local file will override
# the global value of that setting.
# 
# See C<perldoc Spork::Config> for details on settings.
################################################################################

# These will be guessed using getpwuid on the real uid

# author_name: Brian Ingerson
# author_email: ingy@cpan.org
# author_webpage: http://search.cpan.org/~ingy/
# copyright_string: Copyright &copy; 2005 Brian Ingerson




# Some styling:

# banner_bgcolor: hotpink
# logo_image: logo.png
# image_width: 350
# auto_scrolldown: 1
# show_controls: 1
# mouse_controls: 0
# link_previous: &lt; &lt; Previous
# link_next: Next &gt;&gt;
# link_index: Index


# Some paths:

# slides_file: Spork.slides
# template_directory: template/tt2
# template_path: 
# - ./template/tt2
# slides_directory: slides

# This one defaults to CWD, and will vary each time you run 'spork -make'
# file_base: /Users/ingy/dev/cpan/Spork/


# These should probably go in ~/.sporkrc/config.yaml if they're wrong

# download_method: wget
# start_command: open slides/start.html

# character_encoding: utf-8



# Change core classes here:

# formatter_class: Spork::Formatter::Kwid


# Set plugin classes here:

# plugin_classes:
# - Spork::S5
# - Spork::S5Theme
# - Spork::S5ThemeFlower
# - Spork::S5ThemeBlackday
# - Kwiki::PerlBlocks

